Default: &defaults
  database: WebShelf.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: WebShelf_test.sqlite3
  <<: *defaults

Staging:
  database: WebShelf_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: WebShelf_production.sqlite3
  poolsize: 100
  <<: *defaults
